# Generated by Django 3.1.7 on 2021-07-03 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField()),
                ('contribution', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('card_type', models.CharField(choices=[('day', 'Recipes_of_the_day'), ('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER')], default='day', max_length=100)),
                ('time_to_cook', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredients', models.TextField()),
                ('prep_method', models.TextField()),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
